### ISSUE TITLE
Support Conan as a package manager in Clion?

### ISSUE THREAD

**Issue by nonovv** [conan-io/conan-clion-plugin#107]
I fond this,  [Support for vcpkg in CLion](https://blog.jetbrains.com/clion/2023/01/support-for-vcpkg-in-clion/)
Here is a discussion about Clion supporting Conan.

> <img width="777" alt="image" src="https://user-images.githubusercontent.com/3770888/228712537-7bb42101-0a9b-4cc8-8ae2-d1e6f32ec6b9.png">

**Comment by memsharded** [comment]
Hi @taianrc 

Thanks for our suggestion.
After 2.0 launch, we have resumed "integrations" work. We have started with the ``cmake-conan`` integration, which could be very useful when using CLion too, and if it works well, it might not need the plugin.
Please have a look to https://github.com/conan-io/cmake-conan/tree/develop2 (the ``develop2`` branch).

Once it is more clear what ``cmake-conan`` will look like for 2.0, we will resume work on the plugins, we are also in contact with CLion tem for this.
