### ISSUE TITLE
Support for configuring individual libraries

### ISSUE THREAD

**Issue by konradx64** [conan-io/conan-clion-plugin#168]
Hi,
I wanted to ask how it is possible to use certain libaries e.g. dynamic? 
And how exactly can I use my own libaries that I have only installed locally? 
At the moment they are just not found.

Thank you

**Comment by czoido** [comment]
Hi @knimix,

Thanks for the question. Yes, it's possible to use your own libraries, and even customize the _conandata.yml_ and _conanfile.py_ that the plugin generates. To do so, you can manually create the _conandata.yml_ and _conanfile.py_ that the plugin would create for you in the root folder of the project and then modify with your own content:

<img width="969" alt="image" src="https://github.com/conan-io/conan-clion-plugin/assets/5045666/38c9ed30-babf-488e-a87c-779f6e45b7f4">

**conanfile.py**
```python
from conan import ConanFile
from conan.tools.cmake import cmake_layout, CMakeToolchain

class ConanApplication(ConanFile):
    package_type = "application"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.user_presets_path = False
        tc.generate()

    def requirements(self):
        requirements = self.conan_data.get('requirements', [])
        for requirement in requirements:
            self.requires(requirement)
```

**conandata.yml**

```yaml
requirements:
  # here you can add your own requirements
  - "mylib/1.0"
```

(Another way to do this is to add any library from the list and then remove it, the plugin will create the files for you and then you can modify them, but you have to remove the comments in the top of the files to those are not overwritten)

There, you can add your requirements to the list, but be aware that using your own custom `conandata.yml` means that you can't add libraries via de plugin any more, you have to handle them yourself.

Hope this helps!

**Comment by konradx64** [comment]
Hi @czoido,
Sorry for the late reply, I can now use my own libaries thank you.
But one thing I still don't understand is how I can use the assimp libary, for example, and explicitly get the dynamic version, or how you generally decide whether a libary is linked statically or dynamically. 

Thank you.

**Comment by czoido** [comment]
Hi @knimix,
Using your dependencies in shared mode is easy, all you have to do is define in your consumer _conanfile.py_ the `default_options` attribute to `shared=True` for your dependencies. Something like:

```python
...

class ConanApplication(ConanFile):
    ...
    default_options = {"*:shared": True}

    def layout(self):
        ...
    ...
```

Please, check the docs about this attribute in recipes: https://docs.conan.io/2/reference/conanfile/attributes.html#default-options

**Comment by konradx64** [comment]
@czoido 
All right, got it, thanks

**Comment by czoido** [comment]
Thanks to you! Do not hesitate to reopen or open other issues if you have any more questions about that
