### ISSUE TITLE
Conan not found when loading CMake because it's running the wrong conan file 

### ISSUE THREAD

**Issue by juansblanco** [conan-io/conan-clion-plugin#172]
Installing the Conan CLion pluging and running the CMake load gives the following error:

<img width="371" alt="image" src="https://github.com/conan-io/conan-clion-plugin/assets/35701596/e75bff1c-1d82-4711-9ddc-081f6f5ceda6">
  
In CMake settings -> Cache variables, the CONAN_COMMAND is set with the path to a _conan_ file.
This file is a text file with the following contents:
```
#!/bin/sh
pyenv exec $(basename "$0") "$@"
```
Changing the path to the _conan.bat_ file in the same folder solves the problem.

This happens with the option of "conan installed in the system" checked. 
Both files are in the same directory, the issue comes from the wrong file being chosen.

**Comment by czoido** [comment]
I think we can consider this closed by https://github.com/conan-io/conan-clion-plugin/pull/171
