### ISSUE TITLE
Plugin is incompatible with #CL-242.20224.384

### ISSUE THREAD

**Issue by imxiaobo** [conan-io/conan-clion-plugin#188]
![image](https://github.com/user-attachments/assets/4ed2f737-7ae4-4d75-97a1-1bb56052871a)
The plugin does not play well with newer CLion build, could you kindly update the plugin to support new CLion versions?

**Comment by czoido** [comment]
Hi @imxiaobo,
Thanks a lot for reporting. We will try to fix as soon as possible.
