### ISSUE TITLE
Allow local directories not just URLs as the source for installing configs

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan-clion-plugin#23]
I keep a conan config in my repo and want the plugin to install it.

**Comment by jgsogo** [comment]
Yes, this should accept any input accepted by Conan command

![image](https://user-images.githubusercontent.com/1406456/62930382-9a324d80-bdbc-11e9-8f0f-df577102349c.png)

**Comment by Lawrencemm** [comment]
@jgsogo Do you want to assign this to me? I'm working on it.
