### ISSUE TITLE
Automatic dependency download doesn't work in CLion 2019.1

### ISSUE THREAD

**Issue by shaglund** [conan-io/conan-clion-plugin#27]
I installed the plugin in CLion 2019.1.3 but the conan dependencies are not downloaded automatically before CMake is run, I have to manually click the install button.

After some investigation it seems the CMakeRunnerStep.Parameters has changed a bit, where getOutputDir() returns java.nio.file.Path instead of java.io.File.

Applying this patch made it work
```
--- a/src/main/java/conan/extensions/CMakeRunnerStepImpl.java
+++ b/src/main/java/conan/extensions/CMakeRunnerStepImpl.java
@@ -49,8 +49,8 @@ public class CMakeRunnerStepImpl implements CMakeRunnerStep {
     private CMakeProfile getCMakeProfile(@NotNull Project project, @NotNull CMakeRunnerStep.Parameters parameters) {
         CMakeWorkspace ws = CMakeWorkspace.getInstance(project);
         for (CMakeModelConfigurationData data : ws.getModelConfigurationData()) {
-            if (FileUtil.filesEqual(data.getGenerationDir(), parameters.getOutputDir())) {
-                return new CMakeProfile(data.getConfigName(), parameters.getOutputDir());
+            if (FileUtil.filesEqual(data.getGenerationDir(), parameters.getOutputDir().toFile())) {
+                return new CMakeProfile(data.getConfigName(), parameters.getOutputDir().toFile());
             }
         }
         return null;
```

**Comment by jgsogo** [comment]
Hi, @shaglund, is this important for you?

If not, I would like to take care of this issue the right way:
1. Add a test exercising this behavior
2. Demonstrate it fails using Travis CI (we should run tests for different CLion versions)
3. Apply the patch

As you see, I'm trying to enhance the CI so we can develop faster, with more confidence without losing quality.

**Comment by shaglund** [comment]
@jgsogo it would be nice to have a proper fix but I can live with my hacky patch a while longer. I guess my patch breaks CLion 2018 so some kind of backwards compatibility handling is probably required as well.

**Comment by Lawrencemm** [comment]
I'd be in favour of deprecating CLion versions before 2018.3 (2018.3 is the first version with the change that causes this).

That would give us one year of supported CLion versions which seems like an OK policy to me.

**Comment by jgsogo** [comment]
2018.3 was released on Nov 27th (https://blog.jetbrains.com/clion/tag/2018-3/), there should be more people using a newer version than an older one (almost one year since then). If someone complains we will deal with it, but right now it is better to make it work for current versions 👍
