### ISSUE TITLE
Unable to install in CLion 2018.2 EAP

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan-clion-plugin#3]
`Plugin 'Conan' is incompatible with this installation` is the error I receive when I try to install version 0.1.2 from zip into CLion 2018.2 EAP, build #CL-182.2371.31

**Comment by DavidZemon** [comment]
You guys got recognition for your plugin in their latest blog post for this EAP release, so I suspect more people will be flocking to you soon :). I'm certainly thrilled to see this plugin, it is definitely needed!

https://blog.jetbrains.com/clion/2018/05/clion-starts-2018-2-eap-sanitizers-gradle-db-performance/
(See the very bottom of the article)

**Comment by yahavi** [comment]
@DavidZemon,
Thanks for reporting this issue!
0.1.3 had been released with a [fix](https://github.com/conan-io/conan-clion-plugin/commit/35d4d43b9f644e13cfde6633f34677c758aa4dca#diff-c197962302397baf3a4cc36463dce5eaR15) for this issue.
We'll appreciate your feedback for that!

**Comment by DavidZemon** [comment]
Working now, thanks!
