### ISSUE TITLE
Show command line in the console each time a command is invoked

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan-clion-plugin#4]
```
Installing CMake profile Debug

PROJECT: Installing /home/david/Documents/DocsLink/Programming/RedLion/wsbu-libs/conanfile.py
Requirements
...
...
```

That amount of output doesn't help me debug the problem, it doesn't help me report issues that I'm having, and it doesn't help me learn Conan if I'm new to it. Please provide the full command being invoked at the top of the console, similar to how CLion prints the CMake line generating Makefiles:

```
/home/david/reusable/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.2371.31/bin/cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/david/Documents/DocsLink/Programming/RedLion/wsbu-libs
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -
...
...
```

**Comment by yahavi** [comment]
@DavidZemon,
Thanks for your important feedback.
We'll look into it and keep you updated.

**Comment by yahavi** [comment]
@DavidZemon,
Conan CLion plugin v1.0.0 is released.
This version includes this feature.
We'll appreciate your feedback for that!

**Comment by DavidZemon** [comment]
Looks great! Thank you! This 1.0.0 release is really nice :)
