### ISSUE TITLE
Consider upgrading Gradle version

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan-clion-plugin#44]
There is a new version of the JDK which is used by JetBrains products 2019.2 and newer.

Upon trying to run Gradle targets for this project in IntelliJ 2019.2 using the new JDK 11, the following message is received:
```
Unable to start the daemon process.

The project uses Gradle 4.6 which is incompatible with Java 11 or newer.

Possible solution:
 - Upgrade Gradle wrapper to 4.8.1 version and re-import the project
 - Use Java 8 as Gradle JVM: Open Gradle settings 
```

We should consider whether there is a problem with simply upgrading the Gradle version.

**Comment by jgsogo** [comment]
Upgrading the tools don't affect the plugin itself, right? My only concern about this is that it should continue working with the same set of CLion versions as before... (I'm sorry for my illiteracy related to Java 🙈 )

**Comment by Lawrencemm** [comment]
I would think so. I'm having to get my head around all this Java business as well. I'll make a PR and see what CI says.

**Comment by Lawrencemm** [comment]
Oh, CI runs without need of PR...

Huh. Check this out: https://travis-ci.com/Lawrencemm/conan-clion-plugin/jobs/225731025

**Comment by jgsogo** [comment]
Hi! I think you need to rebase your branch on top of `dev`, I've modified the CI scripts (now they work)... and Travis will run if you have the repo activated in your Travis account, yes there is no need to create a PR (and Conan organization will save CI resources).
