### ISSUE TITLE
Need to be able to do `--build missing`

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan-clion-plugin#5]
I rely _heavily_ on `--build missing` because our CI server doesn't have enough power to build every conceivable version of all of our packages every time we commit. I need the Conan plugin in CLion to be able to add `--build missing` and, when invoked with `--update`, also add `--build outdated`.

**Comment by memsharded** [comment]
Maybe a configurable command line for adding args to ``conan install`` call is the simplest and more versatile approach.

**Comment by DavidZemon** [comment]
Yep, sounds like the right approach.

**Comment by yahavi** [comment]
https://github.com/conan-io/conan-clion-plugin/pull/14

**Comment by DavidZemon** [comment]
I'll close this out since it's clearly a duplicate
