### ISSUE TITLE
Does not respect generation Path

### ISSUE THREAD

**Issue by dab0bby** [conan-io/conan-clion-plugin#54]
In my case I'd like to use a `build` output directory where the cmake build folders e.g. `cmake-build-debug` are located.
So I set them in the Clion CMake settigs and CLion resprects them correctly and the output is generated within e.g. `<project_root>/build/cmake-build-debug`. That works like expected.

When hitting Install on the conan plugin this settings is not respected. Conan creates new folder in the project root and moves content into that directory rather then the configured configuration path.

**Comment by jgsogo** [comment]
Hi, @dab0bby. It looks like it is a bug indeed. I've just tested it and although we are apparently using the [target dir from the CMake profile](https://github.com/conan-io/conan-clion-plugin/blob/7aff34c365a08d3e86f0440562a43d18a7493366/src/main/java/conan/commands/Install.java#L35) it is not working as expected.

Thanks for submitting this issue.

**Comment by dab0bby** [comment]
Shouldn't it be the [CMAKE_BINARY_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_BINARY_DIR.html)?

**Comment by jgsogo** [comment]
Yes, it should be that directory, I thought that the class `CMakeProfile` was something provided by CLion API, but no, that class is owned by us... and doesn't contain the information we need.

I need to access the actual `CMakeSettings` instance to retrieve the `generationDir`.

I'm already working on the fix 😉

**Comment by jgsogo** [comment]
After changing the API to >2018.3 the problem seems to be resolved without any further change, it looks like the bug was on the API side... anyway, let's leave this issue open, we need to **add a test to check this scenario**.

**Comment by jgsogo** [comment]
I created https://github.com/conan-io/conan-clion-plugin/issues/67 , we really need end-to-end tests but it's not going to be possible for this release 😞
