### ISSUE TITLE
No profiles to match up

### ISSUE THREAD

**Issue by DEGoodmanWilson** [conan-io/conan-clion-plugin#7]
When I attempt to match profiles, I get this window:

![image](https://user-images.githubusercontent.com/521866/40988170-b33295a6-68ea-11e8-899c-b148d03e9f3f.png)

I am likely doing something wrong, but I'm unsure what.

**Comment by DEGoodmanWilson** [comment]
Curious, it cleared up after restarting CLion again.

**Comment by memsharded** [comment]
Thanks for testing this plugin. Please re-open if it ever happens again!
