### ISSUE TITLE
Options within profile don't effect Clion's CMake configure

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan-clion-plugin#81]
I would be better if the cmake configure was done via conan so that the right cmake definitions were set based on logic in the build step.

```
conan build --configure -if cmake-build-debug -bf cmake-build-debug .
```

**Comment by Hopobcn** [comment]
In theory you could use conan toolchains (+1.30) to forward all cmake definitions from conan.

For instance, in your `conanfile.py` add:
```
    def toolchain(self):
        tc = CMakeToolchain(self)
        tc.preprocessor_definitions["ENABLE_TESTS"] = self.options.build_tests
        tc.write_toolchain_files()
```

Next in CLion `Build, Execution, Deployment` > `CMake`-> `CMake options` pass `-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`.

Then all definitions specified in conan install phase will be forwarded to cmake.

```
$ cat conan_toolchain.cmake | grep ENABLE_TESTS
set(ENABLE_TESTS "True" CACHE STRING "Value assigned from the Conan toolchain" FORCE)
```
