### ISSUE TITLE
Improve error message when no "conan" is installed

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-clion-plugin#9]
I think the only symptom is that the profile list gets no filled, but would be great if the plugin can print an error if "conan" executable is not found.

**Comment by memsharded** [comment]
Actually it would be nice if the plugin:
- Shows the conan version currently running
- Allows for configuring the conan version to run, specially for conan running inside python virtualenv

**Comment by lasote** [comment]
> Allows for configuring the conan version to run, specially for conan running inside python virtualenv

I think that is a little out of scope

**Comment by memsharded** [comment]
Not sure. Many users run conan in a virtualenv, current setup doesn't allow that (the only workaround is to launch CLion inside the virtualenv, but that is not something that users will do)

**Comment by lasote** [comment]
Managing virtualenvs (as pycharm does) could be a more complex feature than the plugin itself. I think users will understand that invoking conan from an IDE require conan in a global scope.

**Comment by yahavi** [comment]
Fixed
