### ISSUE TITLE
Cannot build against CLion 2020.3

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan-clion-plugin#94]
Following imports don't work anymore: 
```
import com.jetbrains.cidr.cpp.cmake.CMakeRunner
import com.jetbrains.cidr.toolchains.CidrToolsUtil;
import com.jetbrains.cidr.PredefinedVariables;
import com.jetbrains.cidr.cpp.cmake.CMakeRunnerStep;
import com.jetbrains.cidr.cpp.toolchains.CPPEnvironment;
import com.jetbrains.cidr.lang.toolchains.CidrToolEnvironment;
import com.jetbrains.cidr.system.HostMachine;
import com.jetbrains.cidr.toolchains.CidrToolsUtil;
import com.jetbrains.cidr.cpp.cmake.model.CMakeModelConfigurationData;
import com.jetbrains.cidr.cpp.cmake.workspace.CMakeWorkspace;
```
I've made a post on the Jetbrains Slack asking for help, will post any findings here.

**Comment by Lawrencemm** [comment]
Answer from Jetbrains Slack:
> Hi!
It’s because some code in CLion was moved from “core” part of CLion into bundled plugins. And now, you have to add these plugins as dependencies.
I suppose you need to add "com.intellij.clion" and  "com.intellij.cidr.base" plugins.
See https://blog.jetbrains.com/clion/2020/12/migration-guide-for-plugins-2020-3/ for more details

**Comment by Eric-Bwr** [comment]
@Lawrencemm can this be closed?

**Comment by czoido** [comment]
I think this can be closed as it refers to the old version of the plugin and we already released a new one, thanks!
